[package]
name = "bevy_pixel_gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_sequence = { path = "bevy_sequence", optional = true }

[features]
sequence = ["dep:bevy_sequence"]
