[package]
name = "bevy_pixel_gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_sequence = { git = "https://github.com/CorvusPrudens/bevy_sequence.git", optional = true }
bevy_tween = "0.7"
rand = "0.8"

[features]
sequence = ["dep:bevy_sequence"]
